edd_user:
    resource: "@EDDUserBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    path: /login_check

logout:
    path: /logout

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"